http {
    limit_req_zone $binary_remote_addr zone=threads_limit:10m rate=90r/m;
    server {
        listen 443 ssl;
        server_name yourdomain.com;
        ssl_certificate /etc/letsencrypt/live/yourdomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yourdomain.com/privkey.pem;
        location /threads {
            limit_req zone=threads_limit burst=10 nodelay;
            proxy_pass http://localhost:PORT_API;
        }
    }
}
